# GNU Make project makefile autogenerated by GENie

.SUFFIXES:

ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = gcc
CXX = g++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

MAKEFILE = bimg_encode.make

ifeq ($(config),debug32)
  OBJDIR              = ../../ios-aarch64/obj/x32/Debug/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeDebug.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG -DBX_CONFIG_DEBUG=1
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m32 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -m32 -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxDebug.a
  LDDEPS             += ../../ios-aarch64/bin/libbxDebug.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR              = ../../ios-aarch64/obj/x32/Release/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeRelease.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG -DBX_CONFIG_DEBUG=0
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m32 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -m32 -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxRelease.a
  LDDEPS             += ../../ios-aarch64/bin/libbxRelease.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = ../../ios-aarch64/obj/x64/Debug/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeDebug.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG -DBX_CONFIG_DEBUG=1
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -m64 -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxDebug.a
  LDDEPS             += ../../ios-aarch64/bin/libbxDebug.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = ../../ios-aarch64/obj/x64/Release/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeRelease.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG -DBX_CONFIG_DEBUG=0
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -m64 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -m64 -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxRelease.a
  LDDEPS             += ../../ios-aarch64/bin/libbxRelease.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  OBJDIR              = ../../ios-aarch64/obj/Debug/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeDebug.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG -DBX_CONFIG_DEBUG=1
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxDebug.a
  LDDEPS             += ../../ios-aarch64/bin/libbxDebug.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR              = ../../ios-aarch64/obj/Release/bimg_encode
  TARGETDIR           = ../../ios-aarch64/bin
  TARGET              = $(TARGETDIR)/libbimg_encodeRelease.a
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG -DBX_CONFIG_DEBUG=0
  INCLUDES           += -I"../../../../bx/include/compat/osx" -I"../../../../bimg/include" -I"../../../../bimg/3rdparty" -I"../../../../bimg/3rdparty/astc-encoder/include" -I"../../../../bimg/3rdparty/iqa/include" -I"../../../../bimg/3rdparty/nvtt" -I"../../../../bimg/3rdparty/tinyexr/deps/miniz" -I"../../../../bx/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef -Wno-class-memaccess -Wno-deprecated-copy
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -O3 -std=c++20 -fno-rtti -fno-exceptions -arch arm64 -Wno-error=unused-command-line-argument -Wno-unused-command-line-argument -Wfatal-errors -Wunused-value -Wundef -Wno-implicit-fallthrough -Wno-shadow -Wno-shift-negative-value -Wno-undef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../ios-aarch64/bin" -arch arm64
  LIBDEPS            += ../../ios-aarch64/bin/libbxRelease.a
  LDDEPS             += ../../ios-aarch64/bin/libbxRelease.a
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(AR)  -rcs $(TARGET)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o \
	$(OBJDIR)/bimg/3rdparty/etc1/etc1.o \
	$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o \
	$(OBJDIR)/bimg/3rdparty/etc2/Tables.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o \
	$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/maths.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o \
	$(OBJDIR)/bimg/3rdparty/libsquish/squish.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o \
	$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o \
	$(OBJDIR)/bimg/src/image_cubemap_filter.o \
	$(OBJDIR)/bimg/src/image_encode.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/bimg/3rdparty/edtaa3 \
	$(OBJDIR)/bimg/3rdparty/etc1 \
	$(OBJDIR)/bimg/3rdparty/etc2 \
	$(OBJDIR)/bimg/3rdparty/iqa/source \
	$(OBJDIR)/bimg/3rdparty/libsquish \
	$(OBJDIR)/bimg/3rdparty/nvtt \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc6h \
	$(OBJDIR)/bimg/3rdparty/nvtt/bc7 \
	$(OBJDIR)/bimg/3rdparty/nvtt/nvmath \
	$(OBJDIR)/bimg/3rdparty/pvrtc \
	$(OBJDIR)/bimg/src \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) $(TARGETDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LIBDEPS) $(EXTERNAL_LIBS) $(RESOURCES) $(OBJRESP) $(LDRESP) | $(TARGETDIR) $(OBJDIRS)
	@echo Archiving bimg_encode
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
endif
	$(SILENT) $(LINKCMD) $(LINKOBJS) 2>&1 > /dev/null | sed -e '/.o) has no symbols$$/d'
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(@)
	-$(call MKDIR,$@)

clean:
	@echo Cleaning bimg_encode
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

ifneq (,$(OBJRESP))
$(OBJRESP): $(OBJECTS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

ifneq (,$(LDRESP))
$(LDRESP): $(LDDEPS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

$(OBJDIR)/bimg/3rdparty/edtaa3/edtaa3func.o: ../../../../bimg/3rdparty/edtaa3/edtaa3func.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/edtaa3
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/etc1/etc1.o: ../../../../bimg/3rdparty/etc1/etc1.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/etc1
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/etc2/ProcessRGB.o: ../../../../bimg/3rdparty/etc2/ProcessRGB.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/etc2
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/etc2/Tables.o: ../../../../bimg/3rdparty/etc2/Tables.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/etc2
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/convolve.o: ../../../../bimg/3rdparty/iqa/source/convolve.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/decimate.o: ../../../../bimg/3rdparty/iqa/source/decimate.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/math_utils.o: ../../../../bimg/3rdparty/iqa/source/math_utils.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/ms_ssim.o: ../../../../bimg/3rdparty/iqa/source/ms_ssim.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/mse.o: ../../../../bimg/3rdparty/iqa/source/mse.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/psnr.o: ../../../../bimg/3rdparty/iqa/source/psnr.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/iqa/source/ssim.o: ../../../../bimg/3rdparty/iqa/source/ssim.c $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/iqa/source
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/alpha.o: ../../../../bimg/3rdparty/libsquish/alpha.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/clusterfit.o: ../../../../bimg/3rdparty/libsquish/clusterfit.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/colourblock.o: ../../../../bimg/3rdparty/libsquish/colourblock.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/colourfit.o: ../../../../bimg/3rdparty/libsquish/colourfit.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/colourset.o: ../../../../bimg/3rdparty/libsquish/colourset.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/maths.o: ../../../../bimg/3rdparty/libsquish/maths.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/rangefit.o: ../../../../bimg/3rdparty/libsquish/rangefit.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/singlecolourfit.o: ../../../../bimg/3rdparty/libsquish/singlecolourfit.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/libsquish/squish.o: ../../../../bimg/3rdparty/libsquish/squish.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/libsquish
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh.o: ../../../../bimg/3rdparty/nvtt/bc6h/zoh.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc6h
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zoh_utils.o: ../../../../bimg/3rdparty/nvtt/bc6h/zoh_utils.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc6h
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohone.o: ../../../../bimg/3rdparty/nvtt/bc6h/zohone.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc6h
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc6h/zohtwo.o: ../../../../bimg/3rdparty/nvtt/bc6h/zohtwo.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc6h
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode0.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode0.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode1.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode1.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode2.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode2.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode3.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode3.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode4.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode4.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode5.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode5.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode6.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode6.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_mode7.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_mode7.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/bc7/avpcl_utils.o: ../../../../bimg/3rdparty/nvtt/bc7/avpcl_utils.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/bc7
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/nvmath/fitting.o: ../../../../bimg/3rdparty/nvtt/nvmath/fitting.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt/nvmath
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/nvtt/nvtt.o: ../../../../bimg/3rdparty/nvtt/nvtt.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/nvtt
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/pvrtc/BitScale.o: ../../../../bimg/3rdparty/pvrtc/BitScale.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/pvrtc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/pvrtc/MortonTable.o: ../../../../bimg/3rdparty/pvrtc/MortonTable.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/pvrtc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcDecoder.o: ../../../../bimg/3rdparty/pvrtc/PvrTcDecoder.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/pvrtc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcEncoder.o: ../../../../bimg/3rdparty/pvrtc/PvrTcEncoder.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/pvrtc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/3rdparty/pvrtc/PvrTcPacket.o: ../../../../bimg/3rdparty/pvrtc/PvrTcPacket.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/3rdparty/pvrtc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/src/image_cubemap_filter.o: ../../../../bimg/src/image_cubemap_filter.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/bimg/src/image_encode.o: ../../../../bimg/src/image_encode.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/bimg/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
